## Documentation: http://docs.travis-ci.com/user/languages/julia/

language: julia

os:
  - linux
  - osx

julia:
  - 1.3
  - nightly

branches:
  only:
  - master

after_success:
  - julia -e 'using Pkg; cd(Pkg.dir("Algorithm101")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'

notifications:
  email: false

## uncomment the following lines to allow failures on nightly julia
## (tests will run but not make your overall status red)
matrix:
 allow_failures:
 - julia: nightly

